version: '2'

services:
  ui:
    build: ./ui
    environment:
      - API_URL=http://petstore.swagger.io/v2/swagger.json
      - VALIDATOR_URL=http://localhost:8080
      - PORT=3000
    ports:
      - 3000:3000
  validator:
    build: ./validator
    ports:
      - 8080:8080
